### ISSUE TITLE
bug: Breadcrumbs component styled incorrectly for RTL

### ISSUE THREAD

**Issue by rehhouari** [saadeghi/daisyui#1598]
### What version of daisyUI are you using?

^2.46.1

### Describe your issue

While having `dir=rtl` the breadcrumbs component is styled incorrectly including:
- the arrows rotation is wrong
- the spacing around the arrows is wrong

To fix it locally for my project I did this:
```css
[dir='rtl'] .breadcrumbs > ul > li + *:before {
  /* this was set to -45deg in rtl */
  --tw-rotate: -135deg;
  /* switched these from the non-rtl code */
  margin-left: 0.75rem;
  margin-right: 0.5rem;
}
```

These modifications fix both the issues I've noticed.

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL (optional)

- Add `dir="rtl"` to https://daisyui.com/components/breadcrumbs/ in DevTools

**Comment by saadeghi** [comment]
Fixed in version `2.50.1`: https://play.tailwindcss.com/YuGfvbSZCv

**Comment by faridvatani** [comment]
@saadeghi 
This problem still persists in this version(`v2.50.1`) and even the last version(`v2.52.0`)

https://play.tailwindcss.com/ORcHt3KhYH
