### ISSUE TITLE
v3: about the disabling of hover effects on mobile

### ISSUE THREAD

**Issue by gurgunday** [saadeghi/daisyui#1886]
### What version of daisyUI are you using?

v3.0

### Describe your issue

I understand the motivation behind this change, but honestly this just broke all interaction animations (including button presses) on mobile. Can't this be a config option instead of being the default? Even if this change stays, I think button press animations should not be disabled in any case.

### Reproduction URL (optional)
https://heyhey.to/HEYHEY
On mobile, buttons simply don't respond to any gesture.

**Comment by saadeghi** [comment]
There is really no reason to allow `:hover` on a device that does not support `hover` because on a touch device there is no cursor to move over elements and leave the element. It's just taps. and if we tap and element with `:hover` the hover effect stays unless we tap another element. It's not a hover behavior at all. It's broken!

Also, probably this will be the default behavior on the next Tailwind CSS release as well: https://twitter.com/adamwathan/status/1664049901322264577

**Comment by gurgunday** [comment]
Okay, I understand why the hover effects were removed, but on iOS, button "presses" don't have any animation either.

Here's an example that demonstrates the change.

Before:
[Tab-1685712747587.webm](https://github.com/saadeghi/daisyui/assets/74139498/b2e287c3-f58e-41a8-b80e-714a82d6b26a)

After:

https://github.com/saadeghi/daisyui/assets/74139498/09127de5-11de-43a4-803c-51ec2b9127d6

Notice how on v2 buttons react to being pressed on. I think this was unintentional?

**Comment by gurgunday** [comment]
@saadeghi sorry for the tag, I just need confirmation that the removal of button **press** animations on iOS is intentional as well so that I don't create another issue 😁

You can check the above videos to see the change I'm talking about. Thanks for the update again, it's great overall!

**Comment by saadeghi** [comment]
@gurgunday The color change of buttons on hover is removed for touch devices and is not coming back (because touch devices keep the element on hover style for ever until you tap somewhere else)

But I see that the click animation (button getting smaller while it is pressed) is also disabled as a side effect. (because that style is also using hover as well)

I'm working on it...

**Comment by saadeghi** [comment]
@gurgunday Should be fixed now on `3.0.2`

**Comment by gurgunday** [comment]
@saadeghi hey, thanks for the quick update! I tested the change but I still see no click animation.

Here's the most recent version (3.0.2):

https://github.com/saadeghi/daisyui/assets/74139498/c43de0fa-9ab7-4889-a24e-c01f8f12f833

The URL: https://heyhey.to/G
