### ISSUE TITLE
bug: Joins cannot be nested

### ISSUE THREAD

**Issue by rinodrummer** [saadeghi/daisyui#2413]
### 1. Checklist

- [X] I updated daisyUI (`npm i -D daisyui@latest`) but I still have this issue
- [X] I looked up into [FAQ](https://github.com/saadeghi/daisyui/discussions/1949) but I couldn't find a solution
- [X] I searched in [existing issues](https://github.com/saadeghi/daisyui/issues?q=is%3Aissue) and [discussion forum](https://github.com/saadeghi/daisyui/discussions?discussions_q=) but this bug has not addressed before
- [X] This bug is dasiyUI issue and it's **NOT** specific to a JS framework or a build tool."

### 2. What version of daisyUI are you using?

v3.9.2

### 3. Which browsers are you seeing the problem on?

Chrome

### 4. Reproduction URL

https://play.tailwindcss.com/p2mVSoZSXy?layout=horizontal

### 5. Describe your issue

I have the necessity to use various join items which represent an entry, each of these entries should have a currency input (I used the `currency-input` class in the Tailwind Play snippet to find out them easily) but noticed that every `:first-child` and `:last-child` in the subtree will be styled as part of the root `join` group.

For example, other then `currency-input`s I marked `acceptance-indicator`s too which shouldn't be styled as part of the `join` but I fixed it out using `.rounded` on it (as shown in the snippet).

But the major issue appears with the `currency-input`s which was formerly thought as an `input-group` and then opted to a `join`.

Right now I can fix it by opting on `input-group`s but, as shown in the documentation, they are going to be deprecated in the next major release so the issue is going to be a real a thing in the future.

I tried to solve the issue by using the `>` (child combinator), but nothing seem to work against the specificity of `:first-child` and `:last-child`, here is my code:

```css
.join > :where(.join-item) {
    border-start-end-radius: 0;
    border-end-end-radius: 0;
    border-end-start-radius: 0;
    border-start-start-radius: 0;
}
.join > .join-item:not(:first-child):not(:last-child),
.join > *:not(:first-child):not(:last-child) > .join-item {
    border-start-end-radius: 0;
    border-end-end-radius: 0;
    border-end-start-radius: 0;
    border-start-start-radius: 0;
}
.join > .join-item:first-child:not(:last-child),
.join > *:first-child:not(:last-child) > .join-item {
    border-start-end-radius: 0;
    border-end-end-radius: 0;
}
.join > .dropdown > .join-item:first-child:not(:last-child),
.join > *:first-child:not(:last-child) > .dropdown > .join-item {
    border-start-end-radius: inherit;
    border-end-end-radius: inherit;
}
.join > :where(.join-item:first-child:not(:last-child)),
.join > :where(*:first-child:not(:last-child) > .join-item) {
    border-end-start-radius: inherit;
    border-start-start-radius: inherit;
}
.join > .join-item:last-child:not(:first-child),
.join > *:last-child:not(:first-child) > .join-item {
    border-end-start-radius: 0;
    border-start-start-radius: 0;
}
.join > :where(.join-item:last-child:not(:first-child)),
.join > :where(*:last-child:not(:first-child) > .join-item) {
    border-start-end-radius: inherit;
    border-end-end-radius: inherit;
}
:where(.join > *) {
    border-radius: inherit;
}
```

**Comment by saadeghi** [comment]
What is your expected output with nested `join`?  
Because `join` makes the first and last item inside it rounded so I'm not sure what would be the reason to nest them? 🤔

**Comment by rinodrummer** [comment]
The fact is that I wasn't directly nesting them for the need to nest them.

I had outer joins which were my entries and an input group inside of it, but since it is marked to be deprecated in the next version, I used joins for both the components and this happened:

Input group:

![The arrow shows which component doesn't render as expected](https://github.com/saadeghi/daisyui/assets/6603220/6ea6a5af-781e-4994-8f7b-17d449990612)

Outer join:

![The begin and the and of the second join item of the outer join don't render as expected too](https://github.com/saadeghi/daisyui/assets/6603220/1b3be9a6-9f0f-4250-9639-354664a9b851)

![The last join item looks like this](https://github.com/saadeghi/daisyui/assets/6603220/c03c9be1-524d-4f4b-83e9-c16a50441c17)

![This element is not a join item but is the first child of a join item and looks like this](https://github.com/saadeghi/daisyui/assets/6603220/84d5fd45-0ebd-4c87-ab76-c6657b9ec730)

I kinda solved the issue on `acceptance-indicator` and `currency-input` [here](https://play.tailwindcss.com/DXvD0W0hmN?layout=horizontal).

**Comment by AndyClausen** [comment]
I have the same issue, but with accordions:
![image](https://github.com/saadeghi/daisyui/assets/16802212/53c6c24b-3b9c-49d8-8ab3-addb096095bd)

This triggers for the first nested element:
![image](https://github.com/saadeghi/daisyui/assets/16802212/41c790d5-09d9-4c54-87af-cd54e4a51ee0)

This is because it's a child of _some_  element that is the last child of element. Adding an empty div in two places per child fixes it for me (added text so you can see where):
![image](https://github.com/saadeghi/daisyui/assets/16802212/78116e9f-f7a4-4401-ac39-afd86f692a02)

The source of the problem is the `*:last-child` which catches _way_ too much. I understand why it was made like this, but maybe someone can think of a better way?

**Comment by whitedark9** [comment]
Same problem while using with accordion which is joined with `join-vertical`. Then, I have some buttons inside it which are joined with `join-horizontal`. I fixed it with css.
```
.join-horizontal :not(:first-child):not(:last-child) {
  @apply !rounded-none;
}
```

**Comment by zvin** [comment]
Hello @saadeghi !

> Because join makes the first and last item inside it rounded

Looking at the examples, I got the impression that `join` an `join-item` are more about removing the rounded corners in the intermediate items. 

> I'm not sure what would be the reason to nest them?

For me it was nested `join`ed `card`s but I guess it could be anything like `join`ed `btn`s in an `accordion`.

I fixed my issue by defining a `join-strict` that only joins its first level children.
It's not as easy to use as `join` but it can be nested, I hope it can be useful for someone else.

```css
/*
 "join-strict" class that joins all its first level children.
 It only works with direct children so "join-item" is no longer necessary.
 It does nothing to margins or padding and you need to specify "flex-row" or "flex-column" manually.

 Logic:

 first and not last: remove bottom border radius
 not first and last: remove top border radius
 not first and not last: remove all border radiuses

 not first: remove top or left border depending on orientation
*/


/*vertical*/
.join-strict.join-vertical > :first-child:not(:last-child) {
	border-end-start-radius: 0;
	border-end-end-radius: 0;
}

.join-strict.join-vertical > :not(:first-child):last-child {
	border-start-start-radius: 0;
	border-start-end-radius: 0;
}

.join-strict.join-vertical > :not(:first-child):not(:last-child) {
	border-start-start-radius: 0;
	border-start-end-radius: 0;
	border-end-start-radius: 0;
	border-end-end-radius: 0;
}

.join-strict.join-vertical > :not(:first-child) {
	border-block-start: 0;
}

/*horizontal*/

.join-strict.join-horizontal > :first-child:not(:last-child) {
	border-start-end-radius: 0;
	border-end-end-radius: 0;
}

.join-strict.join-horizontal > :not(:first-child):last-child {
	border-start-start-radius: 0;
	border-end-start-radius: 0;
}

.join-strict.join-horizontal > :not(:first-child):not(:last-child) {
	border-start-start-radius: 0;
	border-start-end-radius: 0;
	border-end-start-radius: 0;
	border-end-end-radius: 0;
}

.join-strict.join-horizontal > :not(:first-child) {
	border-inline-start: 0;
}
```

Thanks for making daisyui, it's awesome.

**Comment by beholdr** [comment]
Unfortunately, this issue still actual for nested accordions with `join` even on v5:
https://play.tailwindcss.com/HaN6Po88e1

But @zvin solution works, thank you.
Hope this will be fixed by default.
