### ISSUE TITLE
bug: daisyui page keeps crashing on arc browser

### ISSUE THREAD

**Issue by bigboggy** [saadeghi/daisyui#3124]
### Which browsers are you seeing the problem on?

Other

### Reproduction URL

https://daisyui.com/

### Describe your issue

The last weeks I've been visiting the page I've experienced strange random crashes of the site on the arc browser. It doesn't happen on Firefox or chrome. Specifically it happens when I go to the components page.

<img width="973" alt="Screenshot 2024-07-05 at 5 38 36 PM" src="https://github.com/saadeghi/daisyui/assets/118861898/a55fd635-65c5-4e0c-aea6-e892bf53f017">

Hope it helps finding some issues, I can't even open up the console, since it crashes completely the browser window.

Best wishes,

Bogdan

**Comment by saadeghi** [comment]
Does it also happen in Chrome?

**Comment by bigboggy** [comment]
@saadeghi I have not experienced that in chrome yet

**Comment by xxRockOnxx** [comment]
@saadeghi yes it does happen in Chrome.

![image](https://github.com/saadeghi/daisyui/assets/11251134/b7dd813c-b7fa-4af8-a93c-6b6c2d61cd84)

**Comment by saadeghi** [comment]
Can you please check if the issue still exists?

**Comment by iamsatyajit05** [comment]
facing the same issue.

sites content renders for a bit, then shows nothing.

I have attached the log from the console
![image](https://github.com/saadeghi/daisyui/assets/92579751/85f3116c-b0cb-48bc-baf5-064ef23efac1)

using brave just for daisy UI website :)

**Comment by saadeghi** [comment]
@iamsatyajit05 Which page is this? Homepage?  
Do you have the issue on all pages?
Do you have the issue with incognito mode as well?

It's challenging to debug this when I can't see the issue myself. I tried all browsers on Mac, Windows, Ubuntu, Android. All working without issues…

**Comment by iamsatyajit05** [comment]
It only happens on Arc, Windows OS.
But not on Arc Incoginrot Window.

**Comment by saadeghi** [comment]
> It only happens on Arc, Windows OS. But not on Arc Incoginrot Window.

Hmm...   
Can you try clearing site data (cache, cookies, localstorage, etc) and see if it fixes the issue?  
Also, are you using any browser extension that could cause the crash?

**Comment by iamsatyajit05** [comment]
The issue is fixed the `AdBlock — block ads across the web` extension was causing the issue.

Previously I only tried clearing site data but never thought about extension.

**Comment by saadeghi** [comment]
@iamsatyajit05 Thanks!  
I think [reporting the issue to Adblock team](https://help.adblockplus.org/hc/en-us/articles/360062870553-Report-an-issue-via-the-Issue-reporter) would help

@bigboggy @xxRockOnxx Are you also using Adblock extension?

**Comment by xxRockOnxx** [comment]
@saadeghi yes. though i tried turning it off and it still happens.

**Comment by bigboggy** [comment]
> @iamsatyajit05 Thanks! I think [reporting the issue to Adblock team](https://help.adblockplus.org/hc/en-us/articles/360062870553-Report-an-issue-via-the-Issue-reporter) would help
> 
> @bigboggy @xxRockOnxx Are you also using Adblock extension?

<img width="185" alt="image" src="https://github.com/user-attachments/assets/8d47b9b4-c1b0-4450-aa28-07b99689b05f">

these are my extentions

**Comment by naithagoni** [comment]
Hi,
I'm encountering issues accessing the `daisyUI` website, even after clearing the cache and cookies, and disabling `AdblockPlus`.

![image](https://github.com/user-attachments/assets/a92c1b41-a6d6-4101-8378-0d68cb29af8e)

![image](https://github.com/user-attachments/assets/7cc0d36a-13d7-4d2f-96da-76f299f4a900)

Furthermore, the utility classes are also not working in my local development environment, despite having properly configured TailwindCSS.
![image](https://github.com/user-attachments/assets/64fb67ca-a443-460b-acf3-ddd3f3b85968)

**Comment by saadeghi** [comment]
I have a feeling the comments on this issue are about different bugs on different versions of different browsers (or extensions)  
Because apparently disabling AdBlock fixed the issue for some while the other comments are about different things.

Anyway the browser crashing issue is a bug from the browser. You should report it to the browser, not here. CSS is a declarative language. It's not acceptable for browsers to "crash" because of CSS. They should either render CSS styles as they're supposed to, or they should ignore the CSS rules they cannot render.

>If I use daisy v4.12.7 it doesn't crash, but from v4.12.8 and up it does crash.

We started using CSS color mix function for CSS scrollbar color since version 4.12.8. it's a stable CSS feature, supported on all major browsers and even the browsers who don't support it, should simply ignore that CSS rule.

This issue is not happening for everyone and I could not reproduce it unfortunately. But I assume it is affecting some users because of some edge case (maybe some special OS version or some specific hardware situation. Idk.) 

Please try updating your browsers to the latest version (because it might be fixed already) and if it didn't help, please report the issue to your browsers.

**Comment by hector** [comment]
@saadeghi I agree with what you said but I think you could consider documenting this somehow, maybe a FAQ?
In day to day development, we need to support a bunch of browsers we can't control and being practical this means downgrading daisyui :(

**Comment by saadeghi** [comment]
@hector Sure. I will.  
Browsers, like any other software have their own bugs. It's common for browsers to release a new "stable" version with a bug that only happens to a small percentage of users but usually they fix it quickly in the next version and since all browsers have automatic updates enabled by default, the issue will simply vanish before users even notice. This could even happen for all the existing web standards. For example next month a version of Chromium might have a bug with sticky CSS elements and suddenly some users might sometimes see a crash happening in their browsers, then they fix the bug and with the next update the same user will see no issue anymore.
