### ISSUE TITLE
bug: Drawer sidebar doesn't close after refresh in in Firefox

### ISSUE THREAD

**Issue by sandram92** [saadeghi/daisyui#4351]
### Reproduction URL (Required)

https://daisyui.com/components/drawer/?lang=en

### What version of daisyUI are you using?

      "daisyui": "^5.1.25",

### Which browsers are you seeing the problem on?

Firefox

### Describe your issue

Drawer sidebar doesn't close after refresh in Firefox

**Comment by pdanpdan** [comment]
Please open a bug report on Firefox that the input values are not reset on refresh.

It looks like it's a feature :)

We can add `autocomplete="off"` to all inputs for Firefox, even if there is nothing to autocomplete on a checkbox

**Comment by saadeghi** [comment]
Which version of Firefox is this?  
I remember Firefox had this bug years ago but it was fixed.

**Comment by pdanpdan** [comment]
Yes, I found it mentioned 14 years ago. 
Still present in latest stable.

**Comment by sandram92** [comment]
Sorry to get back so late, I've just left that issue, but my QA spot this once again  and autocomplete="off" resolved. Thank you
